server:
  port: 8083
spring:
  application:
    name: inventory-service
  cloud:
    discovery:
      enabled: true
  datasource:
    url: jdbc:mysql://localhost:3306/msdb-product
    username: root
    password:
  jpa:
    hibernate:
      ddl-auto: create
management:
  endpoints:
    web:
      exposure:
        include: "*"
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
