server:
  port: 8084
spring:
  application:
    name: billing-service
  cloud:
    discovery:
      enabled: true
  datasource:
    url: jdbc:mysql://localhost:3306/msdb-billing
    username: root
    password:
  jpa:
    hibernate:
      ddl-auto: create
